"""
demo.py — offline demonstration of the RAG pipeline.

This script does not require a running Streamlit server. It:
  1. Creates a small in-memory document corpus (no PDF file needed).
  2. Splits the corpus into chunks.
  3. Embeds the chunks with the local HuggingFace model.
  4. Builds a FAISS vector index.
  5. Runs several natural-language queries against the index.
  6. (Optional) calls the Groq LLM to generate answers when
     GROQ_API_KEY is set in the environment.

Run:
    python3 demo.py

Environment variables (optional):
    GROQ_API_KEY   — if set, answers will be generated by Groq Llama3.
                     If not set, the script prints retrieved chunks only.
"""

import os
import sys
import textwrap
import logging

logging.basicConfig(level=logging.WARNING)

# ── Sample corpus ─────────────────────────────────────────────
SAMPLE_DOCUMENTS = [
    {
        "title": "Introduction to Neural Networks",
        "content": textwrap.dedent("""\
            A neural network is a computational model loosely inspired by the structure
            of the human brain. It consists of layers of interconnected nodes, or neurons,
            each of which applies a simple non-linear transformation to its inputs.

            The first layer is the input layer, which receives raw feature vectors. The
            last layer is the output layer, which produces predictions. Layers in between
            are called hidden layers. Networks with many hidden layers are called deep
            neural networks, and training them is the subject of deep learning.

            Training a neural network means adjusting the weights on connections between
            neurons so that the network's output matches desired targets on a training set.
            This is done by computing a loss function that measures prediction error and
            then propagating gradients backward through the network using the
            backpropagation algorithm.

            Common activation functions include ReLU (Rectified Linear Unit), sigmoid,
            and tanh. ReLU is preferred in modern deep networks because it does not
            saturate for positive inputs, which helps gradients flow during training.
        """),
    },
    {
        "title": "Retrieval-Augmented Generation",
        "content": textwrap.dedent("""\
            Retrieval-Augmented Generation (RAG) is a framework that combines a retrieval
            system with a generative language model to produce more accurate and grounded
            responses. The core idea is that instead of relying solely on knowledge encoded
            in model weights, the system first retrieves relevant passages from an external
            document corpus, then provides those passages as context to the language model.

            The retrieval step typically uses dense embeddings. Each document chunk is
            encoded into a fixed-dimensional vector by an embedding model. At query time
            the question is encoded with the same model, and the nearest neighbours in
            vector space are returned as context.

            FAISS (Facebook AI Similarity Search) is a popular library for approximate
            nearest-neighbour search over large embedding collections. It provides
            efficient indexing structures such as flat L2, IVF (Inverted File), and HNSW
            (Hierarchical Navigable Small World) graphs.

            The generation step takes the retrieved chunks together with the original
            question and constructs a prompt that is sent to a large language model such
            as GPT-4 or Llama3. The model is instructed to answer only from the provided
            context, which reduces hallucinations and allows the system to cite sources.
        """),
    },
    {
        "title": "Vector Databases",
        "content": textwrap.dedent("""\
            A vector database is a data store optimised for storing and querying
            high-dimensional embedding vectors. Unlike traditional relational databases
            that index scalar values, vector databases index continuous vector
            representations and support similarity search operations such as k-nearest
            neighbours (kNN) and approximate nearest neighbours (ANN).

            Popular vector databases include Pinecone, Weaviate, Qdrant, Chroma and
            Milvus. FAISS is a library rather than a full database but is widely used
            for in-process similarity search. Each system offers trade-offs between
            query latency, indexing throughput, recall accuracy and operational
            complexity.

            Similarity is typically measured with cosine similarity or Euclidean
            distance. Cosine similarity is preferred when the magnitude of vectors
            should not affect ranking, for example with sentence embeddings where
            the direction encodes semantic meaning.
        """),
    },
]

DEMO_QUERIES = [
    "What is backpropagation and why is it used?",
    "How does the retrieval step work in RAG?",
    "What is FAISS and what is it used for?",
    "What activation functions are common in neural networks?",
    "What is the difference between RAG and a standard language model?",
]


def build_vectorstore(documents: list):
    """Embed documents and build a FAISS vector index."""
    from langchain.schema import Document
    from langchain_text_splitters import RecursiveCharacterTextSplitter
    from langchain_community.vectorstores import FAISS
    from langchain_community.embeddings import HuggingFaceEmbeddings

    print("Loading embedding model (all-MiniLM-L6-v2)...")
    embeddings = HuggingFaceEmbeddings(
        model_name="all-MiniLM-L6-v2",
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True},
    )

    raw_docs = [
        Document(
            page_content=doc["content"],
            metadata={"title": doc["title"], "source": doc["title"]},
        )
        for doc in documents
    ]

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=400,
        chunk_overlap=40,
        length_function=len,
        add_start_index=True,
    )
    chunks = splitter.split_documents(raw_docs)
    print(f"Split corpus into {len(chunks)} chunks.")

    print("Building FAISS index...")
    vectorstore = FAISS.from_documents(chunks, embeddings)
    print("Vector index ready.\n")
    return vectorstore


def retrieve_context(vectorstore, query: str, k: int = 3) -> list:
    """Return the top-k most relevant chunks for a query."""
    return vectorstore.similarity_search(query, k=k)


def generate_answer(query: str, context_docs: list, api_key: str) -> str:
    """Call the Groq LLM to generate an answer from retrieved context."""
    from langchain_groq import ChatGroq
    from langchain.prompts import PromptTemplate
    from langchain.chains import RetrievalQA

    context_text = "\n\n".join(
        f"[{doc.metadata.get('title', 'Document')}]\n{doc.page_content}"
        for doc in context_docs
    )

    prompt_text = (
        "Use the following context to answer the question accurately and concisely.\n"
        "If the answer is not in the context, say "
        "\"I couldn't find this information in the provided documents.\"\n\n"
        "Context:\n{context}\n\n"
        "Question: {question}\n\nAnswer:"
    )

    from langchain.prompts import PromptTemplate
    from langchain_groq import ChatGroq
    from langchain_core.output_parsers import StrOutputParser
    from langchain_core.runnables import RunnablePassthrough

    prompt = PromptTemplate(
        template=prompt_text,
        input_variables=["context", "question"],
    )

    llm = ChatGroq(
        model_name="llama3-8b-8192",
        temperature=0,
        groq_api_key=api_key,
    )

    chain = prompt | llm | StrOutputParser()
    return chain.invoke({"context": context_text, "question": query})


def run_demo():
    """Execute the full demonstration pipeline."""
    separator = "-" * 72

    print(separator)
    print("RAG Pipeline Demo")
    print(separator)
    print(
        "Corpus: 3 inline documents covering neural networks, RAG, "
        "and vector databases."
    )
    print()

    # Build the vector index
    try:
        vectorstore = build_vectorstore(SAMPLE_DOCUMENTS)
    except ImportError as e:
        print(f"Missing dependency: {e}")
        print("Run:  pip install -r requirements.txt")
        sys.exit(1)

    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    if api_key:
        print("GROQ_API_KEY found — answers will be generated by Groq Llama3.\n")
    else:
        print(
            "GROQ_API_KEY not set — printing retrieved chunks only.\n"
            "Set GROQ_API_KEY to also see generated answers.\n"
        )

    # Run each query
    for i, query in enumerate(DEMO_QUERIES, 1):
        print(separator)
        print(f"Query {i}: {query}")
        print()

        chunks = retrieve_context(vectorstore, query, k=3)

        print("Retrieved context chunks:")
        for j, chunk in enumerate(chunks, 1):
            title = chunk.metadata.get("title", "Document")
            snippet = chunk.page_content[:200].replace("\n", " ")
            print(f"  [{j}] {title}: {snippet}...")
        print()

        if api_key:
            try:
                answer = generate_answer(query, chunks, api_key)
                print(f"Generated answer:\n{textwrap.fill(answer, width=72)}")
            except Exception as e:
                print(f"LLM call failed: {e}")
        print()

    print(separator)
    print("Demo complete.")
    print(separator)


if __name__ == "__main__":
    run_demo()
